// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Naivart.Database;

namespace Naivart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211207083641_init16")]
    partial class init16
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Naivart.Models.Entities.Kingdom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("Naivart.Models.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Naivart.Models.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("KingdomId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Naivart.Models.Entities.Kingdom", b =>
                {
                    b.HasOne("Naivart.Models.Entities.Location", "Location")
                        .WithOne("Kingdom")
                        .HasForeignKey("Naivart.Models.Entities.Kingdom", "LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Naivart.Models.Entities.Player", b =>
                {
                    b.HasOne("Naivart.Models.Entities.Kingdom", "Kingdom")
                        .WithOne("Player")
                        .HasForeignKey("Naivart.Models.Entities.Player", "KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Naivart.Models.Entities.Kingdom", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("Naivart.Models.Entities.Location", b =>
                {
                    b.Navigation("Kingdom");
                });
#pragma warning restore 612, 618
        }
    }
}
