USE naivart;
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('food', 1, 1, 123456, 1);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('gold', 1, 1, 123456, 1);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('food', 1, 1, 123456, 2);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('gold', 1, 1, 123456, 2);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('food', 1, 1, 123456, 3);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('gold', 1, 1, 123456, 3);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('food', 1, 1, 123456, 4);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('gold', 1, 1, 123456, 4);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('food', 1, 1, 123456, 5);
INSERT INTO resources (type, amount, generation, updatedAt, kingdomId) VALUES ('gold', 1, 1, 123456, 5);
